name: "Deploy Frontend to Production"

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /app/home
            git pull origin main
            npm install
            npm run build
            pm2 describe appfolio-home > /dev/null \
              && pm2 restart appfolio-home \
              || pm2 start npm --name "appfolio-home" -- start

